### ISSUE TITLE
Meta-issue: club-member-request

### ISSUE THREAD

**Issue by Diwakar-Gupta** [SST-OSS/club-onboarding#1]
This issue is supposed to be fixed by all the listed members by providing their github_handle. please follow the steps:-

- fork the repository.
- create a new branch in your forked repository with your name.
- inside the [members](https://github.com/SST-OSS/club-onboarding/tree/main/members) folder create a new file, filename should be your github username.
- inside the file, add the following things:
```
name: <your name> //for ex: Arth
github_handle: <your_github_handle> //for ex: probablyarth
```
- commit the changes and push it to your forked repository.
- open a PR and wait for it to get merged 🥳

## Participants pr

- [x] Abhinav Gupta #12 
- [ ] Abhinav Nagar
- [x] Aditya Prasad Dash #40 
- [x] Aman Anand #11 
- [ ] Amritesh Indal
- [x] Archisman Midya #10
- [x] #4
- [ ] Bishal Jena
- [x] Diwakar Gupta #3 
- [ ] Harshit Shah
- [x] Ishan Avasthi #23 
- [x] Krishna Patidar #39 
- [ ] Krupakar Reddy
- [ ] Kushi Varadaraj
- [ ] Manish Rachakonda
- [ ] Naga Chaitanya Varma
- [x] NARASIMHA #9 
- [ ] Neel Dholiya
- [x] Parth Arora #74 
- [x] Prem Shah #8 
- [ ] Pritam Raj
- [ ] PRIYANSHU BAUL MAJUMDER
- [ ] Sachin
- [x] Samrudh V Vandakudari #21 
- [ ] Satish Rathod
- [x] Shrinibas Mahanta #6 
- [ ] Siddham Jain
- [x] Srujan Reddy Dharma #69 
- [ ] Suryansh Shakya
- [ ] Sushant Singh Chauhan
- [ ] Udit Kumar Nayak
- [x] Varun Deep Saini #18 
- [ ] Zaid Sharieff

**Comment by probablyArth** [comment]
Dont close this issue! @2k4sm
