### ISSUE TITLE
Meta-issue: Track added java problems

### ISSUE THREAD

**Issue by Diwakar-Gupta** [SST-OSS/club-onboarding#72]
This is a meta issue to keep track of all the new java probelms that is created.

- [x] Max and Min of an Array
- [x] Reverse Array
- [x] Pair Count
- [x] Special Subsequences "AG"
- [x] Check Palindrome
- [x] K Occurrences
- [ ] Power of 2 #42
- [ ] Power of 4 #43
- [ ] Two Sum #45
- [ ] Remove duplicates from sorted array #46
- [ ] find-the-index-of-the-first-occurrence-in-a-string #47
- [ ] number-of-1-bits #48
- [ ] Contains Duplicate #49
- [ ] Special Pythagorean triplet #50
- [ ] 10001st Prime #51
- [ ] Factorial Digit Sum #52
- [ ] Summation of primes #53
- [ ] sum of digits in a number #54
- [ ] Is A Number Prime #55
- [ ] Count all primes till N #56
- [ ] Permuted Multiples #57
- [ ] Kth distinct String #58
- [ ] Sort the people #59
- [ ] Find Common Characters #60
- [ ] count-the-number-of-consistent-strings #61
- [ ] Reverse String #62
- [ ] Sorting the sentence #63
- [ ] FizzBuzz #64
- [ ] find-greatest-common-divisor-of-array #65
- [ ] Divisor Game #66
- [ ] FInd GCD & LCM #67
- [ ] Reverse a number #68
